insert into employees (employee_id, name, designation, email, address, access_level, password) values (1, 'Jessica Scoggins', 'Manager', 'jscoggins0@eventbrite.com', 'Apt 1306', 4, 'e2499');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (2, 'Madonna Heigold', 'Nurse', 'mheigold1@sbwire.com', 'PO Box 11084', 3, 'k2377');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (3, 'Valaria Purchase', 'Nurse', 'vpurchase2@tripod.com', '11th Floor', 4, 'c3069');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (4, 'Dacie Linney', 'Veterinarian', 'dlinney3@reverbnation.com', 'Room 206', 3, 'k1753');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (5, 'Ikey Ateridge', 'General Staff', 'iateridge4@miitbeian.gov.cn', '9th Floor', 2, 'n1413');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (6, 'Stephana Necrews', 'Veterinarian', 'snecrews5@businesswire.com', '7th Floor', 1, 'b7606');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (7, 'Matthiew Botte', 'Manager', 'mbotte6@xing.com', 'PO Box 16701', 3, 'c4166');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (8, 'Jenna Zorzetti', 'General Staff', 'jzorzetti7@whitehouse.gov', 'Suite 89', 2, 'e2852');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (9, 'Steffie Patkin', 'Receptionist', 'spatkin8@hud.gov', 'Suite 64', 3, 's6029');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (10, 'Abbey Shelly', 'Nurse', 'ashelly9@bloglines.com', 'Room 1314', 4, 'f5736');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (11, 'Sashenka Haythorn', 'Nurse', 'shaythorna@simplemachines.org', 'Suite 21', 2, 'g0525');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (12, 'Dane Causey', 'Manager', 'dcauseyb@hp.com', 'Suite 17', 3, 'x4407');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (13, 'Essa Angelini', 'Veterinarian', 'eangelinic@sphinn.com', 'Suite 89', 4, 'l9418');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (14, 'Caleb Clashe', 'Veterinarian', 'cclashed@discovery.com', 'Apt 1811', 1, 'e7635');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (15, 'Sherilyn Huddy', 'Receptionist', 'shuddye@paginegialle.it', 'PO Box 63060', 3, 'a7542');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (16, 'Tommy Le Prevost', 'Receptionist', 'tlef@smh.com.au', 'Room 159', 3, 'o7553');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (17, 'Liliane Scammell', 'Manager', 'lscammellg@japanpost.jp', 'PO Box 75373', 3, 'l7201');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (18, 'Korney Stopforth', 'General Staff', 'kstopforthh@cbslocal.com', '2nd Floor', 1, 'd1836');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (19, 'Hildy Narracott', 'General Staff', 'hnarracotti@cdc.gov', 'PO Box 28874', 2, 'a7811');
insert into employees (employee_id, name, designation, email, address, access_level, password) values (20, 'Sherlocke Bunston', 'Receptionist', 'sbunstonj@hhs.gov', 'Suite 88', 4, 'y8651');
